### ISSUE TITLE
Post title link on index page error

### ISSUE THREAD

**Issue by arjunsajeev** [poole/lanyon#108]
Post title link in the index page is  not working for repositories of the type `username.github.io`.It generates links of the form `http://0.0.7.223/04/29/new-blog-post/`I think the post title link in the index page only requires `{{ post.url }}` instead of `{{ site.baseurl }}/{{ post.url }}`

**Comment by jakefb** [comment]
I'm having the same issue :(

**Comment by Siyfion** [comment]
I am also suffering from this issue, however it could be a configuration thing that I'm missing... (Sorry @mdo if this is spurious!)

**Comment by gogozs** [comment]
comment out `url` line, and set `baseurl: ""`.

 works for me on github user page.

**Comment by ryano88** [comment]
The correct fix for this is to leave _config.yml as it is and change

    {{site.baseurl}}/{{post.url}}

To

    {{site.baseurl}}{{post.url}}

In index.html

The problem is caused by the fact that `{{post.url}}` has a leading `/`

**Comment by jakefb** [comment]
Worked for me thanks @ryano88!

**Comment by wireddown** [comment]
In short, here are the best practices for User pages:

## _config.yml
* `baseurl` must be empty

## Theme layouts and includes
* Always concatenate Jekyll and Liquid tags in links, eg: `href="{{ site.baseurl }}{{ post.url }}"`
* Always start links with `{{ site.baseurl }}`
* Otherwise, always use a trailing slash after `{{ site.baseurl }}` in links

More details and command-line validation: [Configuring Jekyll for User and Project GitHub Pages](http://downtothewire.io/2015/08/15/configuring-jekyll-for-user-and-project-github-pages/)

**Comment by Autodidact24** [comment]
Hi,
I was able to solve this issue as suggested by @ryano88. However, when clicking to the title, the page that appears is ill formatted.
My blog can be found here: http://shubhamtomar.me/
Try clinking on any title: http://shubhamtomar.me/2015/05/15/Twitter-Sentiment-Analysis/.

**Comment by wireddown** [comment]
Your `head.html` include page has an incorrect link to the CSS, so the Lanyon styling is never loaded. Change its `href` URLs to `{{ site.baseurl }}/public/css/lanyon.css`; notice the slash before public. See the last bullet in my response above, or visit my link for instructions on how to inspect the rest of your site for correctness.

**Comment by socpriya** [comment]
Worked for me. 
Thanks @ryano88!!!

**Comment by keeprock** [comment]
@ryano88 thanks for saving my precious time! Have a great day, brother!
