### ISSUE TITLE
Gray in toggle button

### ISSUE THREAD

**Issue by dyskette** [poole/lanyon#109]
Using a color theme, e.g. `theme-base-08`, there is gray in all the actions of the button. Here I show normal, active and return to normal.

![theme-buttons-bug](https://cloud.githubusercontent.com/assets/6687927/7477613/9b7baa18-f31a-11e4-9f28-646a5dac4154.png)

**Comment by jakefb** [comment]
I'm also affected by this

**Comment by nicholaelaw** [comment]
Is this fixed yet? If not, I've come up with a simple solution.

Find the following style in `Lanyon.css`:

    .sidebar-toggle:active:before,
    #sidebar-checkbox:focus ~ .sidebar-toggle:before,
    #sidebar-checkbox:checked ~ .sidebar-toggle:before {
      ...
    }

Notice how the button is generated via linear gradient instead of an image or icon. Next, in the content, replace all `#555` with `rbga(0,0,0,0)`. This changes the hardcoded grey into transparent. The button should be displaying properly now.

<img width="87" alt="lanyon-button-fixed" src="https://cloud.githubusercontent.com/assets/10719482/9835380/038680d0-5a1b-11e5-8f91-d9db9c93a96b.png">
