### ISSUE TITLE
Massive build time for large site

### ISSUE THREAD

**Issue by joacimmelin** [poole/lanyon#125]
Hi,

I have close to 7000 posts on my blog and wanted to use Lanyon as a theme. Since Lanyon builds a separate directory for every year with subdirectories for month, day and each post that day plus a directory for each page, it absolutely kills my (Linux based) server when I try to build the site with build times up to two hours. 

I tried building it on my Core i7 Macbook Pro (16GB RAM, fast flash storage) and it's close to one hour to build the site.

I understand that most people don't keep blogs this size very often but if, or when, you are looking at a re-design, I would love if you would keep this in mind. I have no idea if there is any way around this "problem" but I'm keeping my fingers crossed.

Thanks,

Joacim

**Comment by nicolasmccurdy** [comment]
Unfortunately this is an issue with Jekyll (the static site generator) and not Lanyon itself. Lanyon cannot fix this issue. Build times take a while with Jekyll because subsequent builds end up rebuilding the entire site from scratch (and I don't think it's because of the directory structure).

Fortunately, [Jekyll 3 is in development](https://github.com/jekyll/jekyll/issues/3324) and plans to fix these performance issues by maintaining a cache and gradually rebuilding the site. Jekyll 3 is not stable yet, but there is a beta build you can use today (though you can't use it on GitHub Pages yet).

**Comment by nicolasmccurdy** [comment]
Sorry, I just noticed your [Not compatible with Jekyll 3.0](Not compatible with Jekyll 3.0) issue.

**Comment by joacimmelin** [comment]
I run Jekyll on mu own server so I can help out with beta testing Lanyon with Jekyll 3 if needed.

**Comment by joacimmelin** [comment]
I've since posting my observations abandoned Jekyll and (reluctantly) returned to Wordpress but I thought I would have a second look now as a few years have past. 

With Jekyll 3.4.3, the current (when posting this) version of Lanyon and with 7400+ posts the first build of the site took almost 8 hours on a eight core Mac Pro with 16GB RAM and a pretty fast SSD. 
A rebuild with the --incremental flag set took just over 47 minutes.  

I guess Jekyll isn't for me as long as I want to use Lanyon.
