### ISSUE TITLE
jekyll-paginate gem is required for usage

### ISSUE THREAD

**Issue by brycepj** [poole/lanyon#159]
If I install `jekyll` fresh (`sudo gem install jekyll`), then: 

```
git clone git@github.com:poole/lanyon.git
cd lanyon/
jekyll serve
```

I get the following error: 

```
Configuration file: /home/bryce/_repos/devbryce/devbryce-jekyll/_config.yml
       Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
            Source: /home/bryce/_repos/devbryce/devbryce-jekyll
       Destination: /home/bryce/_repos/devbryce/devbryce-jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Since v3.0, permalinks for pages in subfolders must be relative to the site source directory, not the parent directory. Check http://jekyllrb.com/docs/upgrading/ for more info. 
```

When I add `gems: [jekyll-paginate]` to `_config.yml`, I find out I need to install the dependency myself. 

```
Configuration file: /home/bryce/_repos/devbryce/devbryce-jekyll/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-paginate or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-paginate' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
jekyll 3.1.2 | Error:  jekyll-paginate
```

Once I install it (`gem install jekyll-paginate`), and then try to `serve`, all is well. 

This seems like this kind of thing that could turn away newcomers or the less tech-savvy, and should be mentioned in the docs.

**Comment by sujith3g** [comment]
same here, @brycepj any solutions  ?

**Comment by funkenstrahlen** [comment]
You are using jekyll 3. This repo is still build for jekyll 2.

**Comment by mafagafogigante** [comment]
Sujith G did the disservice of deleting his comment, making @funkenstrahlen's answer really strange there.

It was

> same here, @brycepj any solutions ?

Well, there are no **solutions** because this is not a problem per se (see what @funkenstrahlen said). @brycepj mentioned how he solved it, you should be able to "fix" it the same way. 

The issue name is somewhat misleading, as that is not a problem by itself and the reporter put his focus on

> should be mentioned in the docs

After teaching the less tech-savvy (whatever that means) how to fix the issue. Kudos for you, @brycepj.

It could be mentioned in the docs, and I do believe that it is a good idea, but there is nothing to "fix" until the repository updates to Jekyll 3, which is not a "standard" as GitHub pages is not the only place in the world where Jekyll is used.

**Comment by qqbuby** [comment]
Please use `sudo gem install jekyll-paginate` to get a local copy
A few quick fixes [Upgrading to Jekyll 3.0](http://kersulis.github.io/2015/10/31/jekyll-3/)

**Comment by drashti4** [comment]
I am using jekyll 3.4.3 but still when same error. I have install paginate and changed config also gems: [jekyll-paginate]

` Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
            Source: /home/drashti/.local/share/Trash/files/localisationofschool
       Destination: /home/drashti/.local/share/Trash/files/localisationofschool/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Since v3.0, permalinks for pages in subfolders must be relative to the site source directory, not the parent directory. Check https://jekyllrb.com/docs/upgrading/ for more info. 
`

**Comment by zach007** [comment]
help me, I have spend a lot of time doing this ...
![image](https://user-images.githubusercontent.com/7594289/43687623-db404174-990a-11e8-94dd-76b7611cb296.png)
and I have install this plugin ... what's wrong ..
![image](https://user-images.githubusercontent.com/7594289/43687633-f464a41a-990a-11e8-86f2-df291ccd0cae.png)
