### ISSUE TITLE
Changing fonts

### ISSUE THREAD

**Issue by lelliphan** [poole/lanyon#96]
I'm new to this, so apologize for the potentially naive question.

If I were to change the font of lanyon to say, https://www.google.com/fonts/specimen/Open+Sans, how would I go about doing that?

**Comment by nicolasmccurdy** [comment]
Lanyon uses web fonts from [Google Fonts](http://www.google.com/fonts/). Both PT Sans (the default font for Lanyon) and Open Sans are on Google Fonts, so you can still use it, you'll just have to switch the font around.

[This line](https://github.com/poole/lanyon/blob/547fe8aeabcc86fd98e5059d842fbc8e3dc738a7/_includes/head.html#L21) includes the CSS file for the PT Sans web font so that we can use it in our CSS. If you pick [Open Sans on Google Fonts](http://www.google.com/fonts#QuickUsePlace:quickUse/Family:Open+Sans), they will give you a line of HTML (under "3. Add this code to your website:") that you can replace that line with to load Open Sans instead of PT Sans and PT Serif. Now, we will have to modify this in our CSS to tell the browser what text we want displayed in Open Sans. The `font-family` property in CSS is used to set fonts (and fallback fonts) for different elements on the page. Now we edit [lanyon.css](https://github.com/poole/lanyon/blob/master/public/css/lanyon.css) to replace all lines with `font-family` to use the CSS code that Google Fonts gave us under "4. Integrate the fonts into your CSS:".

**Comment by lelliphan** [comment]
That works. Thank for clarifying!

**Comment by KorGunnlind** [comment]
this helped me greatly. Thnx guys!
